import { chromium } from "playwright-core";
const base = process.env.BASE ?? "http://localhost:4173";
const b = await chromium.launch({ executablePath: "/usr/bin/google-chrome", args: ["--no-sandbox"] });
const errors = [];
const V = process.env.V ?? "a";
import { mkdirSync } from "node:fs"; mkdirSync(`docs/screens/${V}`, { recursive: true });
for (const [name, w, h] of [["desktop", 1280, 900], ["mobile", 390, 844]]) {
  const p = await b.newPage({ viewport: { width: w, height: h } }); p.on("dialog", (d) => d.accept());
  p.on("pageerror", (e) => errors.push(name + " " + e.message));
  p.on("console", (m) => m.type() === "error" && errors.push(name + " console " + m.text()));
  await p.goto(base + "/?v=" + V); await p.waitForSelector("h1"); await p.waitForTimeout(900);
  await p.screenshot({ path: `docs/screens/${V}/${name}-dashboard.png`, fullPage: false });
  await p.goto(base + "/session/?mode=qcm"); await p.getByRole("button", { name: "Commencer" }).click();
  await p.waitForSelector('[role="radiogroup"]');
  await p.screenshot({ path: `docs/screens/${V}/${name}-qcm.png` });
  await p.keyboard.press("1"); await p.waitForTimeout(200); await p.getByRole("button", { name: /Valider/ }).click().catch(()=>{}); await p.waitForTimeout(500);
  await p.screenshot({ path: `docs/screens/${V}/${name}-qcm-feedback.png` });
  await p.goto(base + "/session/?mode=flashcards"); await p.getByRole("button", { name: "Commencer" }).click();
  await p.waitForTimeout(300); await p.keyboard.press(" "); await p.waitForTimeout(700);
  await p.screenshot({ path: `docs/screens/${V}/${name}-flashcard.png` });
  await p.goto(base + "/session/?mode=qcm"); await p.getByRole("button", { name: "Commencer" }).click();
  await p.waitForSelector('[role="radiogroup"]'); await p.keyboard.press("1"); await p.waitForTimeout(200);
  await p.getByRole("button", { name: "Terminer" }).click(); await p.waitForTimeout(500);
  const conf = p.getByRole("button", { name: /Terminer|Oui|Confirmer/ }); if (await conf.count()) await conf.last().click().catch(()=>{});
  await p.waitForTimeout(500); await p.screenshot({ path: `docs/screens/${V}/${name}-results.png` });
  await p.goto(base + "/library/"); await p.fill('input[aria-label="Recherche"]', "IGB"); await p.waitForTimeout(300);
  await p.screenshot({ path: `docs/screens/${V}/${name}-library.png` });
  await p.goto(base + "/schemas/"); await p.waitForSelector("h1"); await p.waitForTimeout(900);
  await p.screenshot({ path: `docs/screens/${V}/${name}-schemas.png` });
  await p.goto(base + "/library/"); await p.fill('input[aria-label="Recherche"]', "Quatre forces"); await p.waitForTimeout(300);
  await p.locator("li button[aria-expanded]").first().click(); await p.waitForTimeout(700);
  await p.screenshot({ path: `docs/screens/${V}/${name}-library-schema.png` });
  const sw = await p.evaluate(() => document.documentElement.scrollWidth - innerWidth);
  console.log(name, "horizontal overflow px:", sw);
}
console.log("errors:", errors.length ? errors : "none");
await b.close();
